### ISSUE TITLE
Unable to use Slash commands

### ISSUE THREAD

**Issue by Lorcan0** [Color-Chan/Color-Chan.Discord#11]
![Screenshot_20211116-021506_Discord](https://user-images.githubusercontent.com/94581310/142334965-0d3b644a-07a1-4cc6-9dcc-7f34110e8472.jpg)
![Screenshot_20211116-021149_Discord](https://user-images.githubusercontent.com/94581310/142334968-75b71e7b-ce6f-47ec-8dbc-6411980112b0.jpg)

The command center comes up for the bot but when clicked on no commands pop up only the ones built into discord itself. 

Note that this is mobile but it still don't work viva desktop either and yes my discord is 100% up to date so idk what is happening.

**Comment by BrammyS** [comment]
Does the bot have the `use application commands` permission?

**Comment by Lorcan0** [comment]
> Does the bot have the `use application commands` permission?

Pretty sure it does.

**Comment by BrammyS** [comment]
Do other commands work :?
Looks like it's a discord related issue btw ;(

**Comment by Lorcan0** [comment]
> Do other commands work :? Looks like it's a discord related issue btw ;(

Uh yes as I'm able to use one for other bots who now use slash commands.

**Comment by BrammyS** [comment]
Mind sending a message in the support server for color-chan? Since this isn't related to the library.
https://colorchan.com/permalinks/support
