### ISSUE TITLE
Bot werkt niet in me server krijg steeds error melding

### ISSUE THREAD

**Issue by Tetouaniaa** [Color-Chan/Color-Chan.Discord#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BrammyS** [comment]
Please go over to our support server for help with Color-Chan. Or describe the issue properly if it is an issue with the library.
And also please keep it in English.
https://colorchan.com/permalinks/support
